services:
  stockeye-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: stockeye-api
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=stockeye-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=stockeye-redis
    depends_on:
      stockeye-db:
        condition: service_healthy
      stockeye-redis:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./src/api:/app/src/api
      - ./src/common:/app/src/common
      - ./logs:/logs
    networks:
      - stockeye-network

  stockeye-bot:
    build:
      context: .
      dockerfile: src/bot/Dockerfile
    container_name: stockeye-bot
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      - API_HOST=stockeye-api
    depends_on:
      stockeye-api:
        condition: service_healthy
    volumes:
      - ./src/bot:/app/src/bot
      - ./src/common:/app/src/common
      - ./logs:/logs
    networks:
      - stockeye-network

  stockeye-db:
    image: postgres:14
    container_name: stockeye-db
    restart: always
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stockeye-network

  stockeye-redis:
    image: redis:7-alpine
    container_name: stockeye-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stockeye-network

  stockeye-worker:
    build:
      context: .
      dockerfile: src/worker/Dockerfile
    container_name: stockeye-worker
    command: python main.py
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=stockeye-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=stockeye-redis
      
    depends_on:
      - stockeye-redis
      - stockeye-db
    volumes:
      - ./src/worker:/app/src/worker
      - ./src/common:/app/src/common
      - ./logs:/logs
    networks:
      - stockeye-network

networks:
  stockeye-network:
    driver: bridge
