services:
  stockeye-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: stockeye-api
    ports:
      - "10082:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=stockeye-db # 서비스 이름으로 호스트 지정
      - REDIS_HOST=stockeye-redis
      - WORKER_HOST=stockeye-worker
    depends_on:
      stockeye-db:
        condition: service_healthy
      stockeye-redis:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./src/api:/app/src/api
      - ./src/common:/app/src/common
      - ./logs:/logs
    networks:
      - stockeye-network

  stockeye-bot:
    build:
      context: .
      dockerfile: src/bot/Dockerfile
    container_name: stockeye-bot
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      - API_HOST=stockeye-api
    depends_on:
      stockeye-api:
        condition: service_healthy
    volumes:
      - ./src/bot:/app/src/bot
      - ./src/common:/app/src/common
      - ./logs:/logs
    networks:
      - stockeye-network

  stockeye-db:
    image: postgres:14
    container_name: stockeye-db
    restart: always
    env_file:
      - .env.${APP_ENV:-development} # .env 파일에 POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB 변수가 정의되어 있어야 합니다.
    ports:
      - "5433:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stockeye-network

  stockeye-redis:
    image: redis:7-alpine
    container_name: stockeye-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - stockeye-network

  stockeye-worker:
    build:
      context: .
      dockerfile: src/worker/Dockerfile
    container_name: stockeye-worker
    command: uvicorn src.worker.main:app --host 0.0.0.0 --port 8001 --workers 4 --reload
    ports:
      - "10081:8001"
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=stockeye-db # 서비스 이름으로 호스트 지정
      - REDIS_HOST=stockeye-redis
    depends_on:
      - stockeye-redis
      - stockeye-db
    volumes:
      - ./src/worker:/app/src/worker
      - ./src/common:/app/src/common
      - ./logs:/logs
    networks:
      - stockeye-network

networks:
  stockeye-network:
    driver: bridge