"""Add notification_preferences to User

Revision ID: a6bb112a92be
Revises: 53c9f347959a
Create Date: 2025-12-02 07:27:26.615990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bb112a92be'
down_revision: Union[str, Sequence[str], None] = '53c9f347959a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('notification_preferences', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'notification_preferences')
    # ### end Alembic commands ###
