"""Add composite index to DailyPrice

Revision ID: c6a65e6a2b74
Revises: a6bb112a92be
Create Date: 2025-12-02 07:41:28.461659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a65e6a2b74'
down_revision: Union[str, Sequence[str], None] = 'a6bb112a92be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_prices_symbol_date', 'daily_prices', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_prices_symbol_date', table_name='daily_prices')
    # ### end Alembic commands ###
