from .user import router as user_router
from .price_alert_router import router as price_alert_router
from .disclosure_alert_router import router as disclosure_alert_router
from .predict import router as predict_router
from .watchlist import router as watchlist_router
from .simulated_trade import router as simulated_trade_router
from .prediction_history import router as prediction_history_router
from .admin import router as admin_router
from .stock_master import router as symbols_router